4896: Remove JS hover class
ding2/ding2 pull request #1673
Opened 2020-08-26 07:35 UTC by xendk

#### Link to issue

https://platform.dandigbib.org/issues/4896

#### Description

The combination of CSS hover effects and JS driven hover effects
causes odd behaviour.

Remove the JS hover effect, the CSS one is just fine.

#### Screenshot of the result

![new-event-overlay-2020-08-26](https://user-images.githubusercontent.com/229422/91274718-6a63a700-e77f-11ea-9573-fd26b86183ce.gif)

#### Checklist

- [x] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [x] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [x] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

2020-09-15 12:39 UTC, JrgenGNielsen requested changes
bit of nitpicking...

2020-09-15 12:39 UTC, JrgenGNielsen commented on themes/ddbasic/sass/components/node/event.scss
> +    // &:hover {
just delete, rather than outcomment

2020-09-16 08:07 UTC, xendk commented on themes/ddbasic/sass/components/node/event.scss
> +    // &:hover {
Doh. Fixed.

2020-09-16 08:25 UTC, xendk commented
Test failure unrelated.

2020-09-16 10:24 UTC, JrgenGNielsen commented
reviewed and approved

2020-10-28 05:41 UTC, merged