5005: Clone page handler properly
ding2/ding2 pull request #1725
Opened 2020-11-25 15:58 UTC by xendk

#### Link to issue

https://platform.dandigbib.org/issues/5005

#### Description

When adding terms, the new variants wasn't properly cloned, resulting in sections sharing content.

Try cloning like `page_manager_handler_clone_submit()` does it instead.

#### Checklist

- [x] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [x] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [x] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

2020-11-25 19:50 UTC, xendk commented
Behat failure is unrelated, and the scrutinizer error is difficult to fix. Page manager itself uses eval when cloning, and avoiding it would require writing a parser that parses enough of the PHP language to turn an export string back into an object.

2020-12-01 14:29 UTC, cableman requested changes

2020-12-01 14:29 UTC, cableman commented on modules/ding_sections/modules/ding_sections_term_panel/ding_sections_term_panel.module
> +  $export = page_manager_export_task_handler(page_manager_load_task_handler('term_view', '', 'term_section_panel_context'));
This "hack" with eval seams like something that needs an inline comment! 

So this loads an pane/panels as an string encode config (like seen in features exports) an creates an new variant of that pane/panel?

2020-12-04 12:23 UTC, cableman approved these changes

2020-12-08 08:27 UTC, merged