Feature/4944 link text accessibility
ding2/ding2 pull request #1752
Opened 2021-02-10 16:31 UTC by yepzdk

#### Link to issue

https://platform.dandigbib.org/issues/4944

#### Description

Add aria attributes to article elements and links to accommodate a better experience for Screenreader users

#### Screenshot of the result

Affects what is read by a Screenreader

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

2021-02-10 16:31 UTC, GitCop commented
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 88c7f14bc298d078a4401a39fe7cc6f63a60e710
  * The subject should be kept around 50 characters long. The subject must not be more than 69 characters long. Strive for about 50 characters.

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

2021-02-10 16:31 UTC, GitCop commented
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 88c7f14bc298d078a4401a39fe7cc6f63a60e710
  * The subject should be kept around 50 characters long. The subject must not be more than 69 characters long. Strive for about 50 characters.

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

2021-02-11 20:06 UTC, cableman commented
The behat test failure is not related to this PR.

2021-04-28 09:43 UTC, JrgenGNielsen requested changes
A question, and a bit of nitpicking

2021-04-29 08:03 UTC, yepzdk commented
@JrgenGNielsen Thank you for your review. I have addressed your comments in the latest commits.

2021-05-05 08:04 UTC, JrgenGNielsen approved these changes

2021-05-05 08:05 UTC, JrgenGNielsen commented
reviewed and approved

2021-05-05 14:10 UTC, merged