5240 place2book returns error
ding2/ding2 pull request #1856
Opened 2022-01-28 10:46 UTC by arniloftsson

#### Link to issue

https://platform.dandigbib.org/issues/5240

#### Description

This PR deals with a error that I have not been able to reproduce. The errors shows up as event_id and event_maker_id get set to 1 and the event loses connection to its counterpart in place2book service. This PR introduces som definsive programming and logging if the error occurs. It hinders the page from saving invalid event_id and event_maker_id to the database. And it changes to place moste likely to cause this errors to a more robust code. It also changes message text that would otherwise be confusing to users.

#### Screenshot of the result

If your change affects the user interface you should include a screenshot of the result with the pull request.

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

2022-01-28 10:46 UTC, GitCop commented
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 87a2c0b16670a7bb5761bed79f92b8acc6bb6764
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

2022-01-28 10:46 UTC, GitCop commented
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 87a2c0b16670a7bb5761bed79f92b8acc6bb6764
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

2022-01-28 10:54 UTC, GitCop commented
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 87a2c0b16670a7bb5761bed79f92b8acc6bb6764
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

2022-03-25 10:12 UTC, kasperg requested changes
:+1: I appreciate the problems in dealing with an error that you cannot reproduce. This is as good as it gets.

I have a few comments for you to look into.

2022-03-25 10:12 UTC, kasperg commented on modules/ding_place2book/ding_place2book.fields.inc
> +                er der desværre ingen anden mulighed end at oprette begivenheden på ny forfra.'), 'error');
Please keep system texts in English.

2022-03-25 10:12 UTC, kasperg commented on modules/ding_place2book/ding_place2book.fields.inc
> +            watchdog('ding_place2book', 'Items to be saved: @items', array('@items' => print_r($items , TRUE)), WATCHDOG_ERROR);
Is there a reason to log this error in multiple entries? If not then consider combining messages and data into a single watchdog entry.

2022-03-25 16:25 UTC, GitCop commented
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 87a2c0b16670a7bb5761bed79f92b8acc6bb6764
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

2022-03-25 16:53 UTC, GitCop commented
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 87a2c0b16670a7bb5761bed79f92b8acc6bb6764
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

2022-03-25 16:53 UTC, GitCop commented
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 87a2c0b16670a7bb5761bed79f92b8acc6bb6764
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

2022-03-25 17:08 UTC, GitCop commented
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 87a2c0b16670a7bb5761bed79f92b8acc6bb6764
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

2022-03-25 17:08 UTC, GitCop commented
Please ensure that your commit messages comply with our contribution guidelines.

 * Commit: 87a2c0b16670a7bb5761bed79f92b8acc6bb6764
  * The first line of your commit message (the subject) must follow this format: [issue number]: [short summary of change]

Guidelines are available at https://github.com/ding2/ding2/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

2022-04-25 08:46 UTC, kasperg approved these changes
:+1: Thanks for the updates.

2022-05-03 08:45 UTC, merged