5448: Add cookie banner placeholders on videos
ding2/ding2 pull request #1912
Opened 2022-09-05 06:08 UTC by xendk

Tell the user they have to accept cookies to view the video,

#### Link to issue

https://platform.dandigbib.org/issues/5448

#### Description

Add cookie banner placeholders on videos that tell the user they have to accept cookies to view the video.

#### Screenshot of the result

![image](https://user-images.githubusercontent.com/229422/188371740-707b533c-bae2-4cb0-8950-c1881d1457de.png)

#### Checklist

- [x] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [x] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [x] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

2022-09-05 06:34 UTC, xendk commented
As usual, the behat test failures are unrelated.

2022-09-05 07:18 UTC, cableman requested changes

2022-09-05 07:18 UTC, cableman commented on modules/ding_content/templates/media-vimeo-video--cookieinformation.tpl.php
> +    <p>Denne video er ikke tilgængelig da du ikke har accepteret marketing-cookies.</p>
Should that have been wrapped in `t()`

2022-09-05 07:18 UTC, cableman commented on modules/ding_content/templates/media-youtube-video--cookieinformation.tpl.php
> +    <p>Denne video er ikke tilgængelig da du ikke har accepteret marketing-cookies.</p>
Should that have been wrapped in `t()`

2022-09-05 07:18 UTC, cableman commented on modules/ting_oembed/ting_oembed.module
> +      $concent->append($dom->createNode('p', 'Denne video er ikke tilgængelig da du ikke har accepteret marketing-cookies.'));
Should that have been wrapped in `t()`

2022-09-05 07:28 UTC, xendk commented on modules/ding_content/templates/media-vimeo-video--cookieinformation.tpl.php
> +    <p>Denne video er ikke tilgængelig da du ikke har accepteret marketing-cookies.</p>
@cableman Fixed.

2022-09-07 07:27 UTC, cableman approved these changes

2022-09-09 09:04 UTC, merged